// <auto-generated />
using System;
using Bronistol.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bronistol.Database.Migrations
{
    [DbContext(typeof(BronistolContext))]
    partial class BronistolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bronistol.Database.DbEntities.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AssignedDateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmitDateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDateId");

                    b.HasIndex("NoteId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("SubmitDateId");

                    b.ToTable("BookingEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.DateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayDate")
                        .HasColumnType("text");

                    b.Property<string>("ShortDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DateEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NoteEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.PriorityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PriorityEntity");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.ReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReasonEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.BookingEntity", b =>
                {
                    b.HasOne("Bronistol.Database.DbEntities.DateEntity", "AssignedDate")
                        .WithMany()
                        .HasForeignKey("AssignedDateId");

                    b.HasOne("Bronistol.Database.DbEntities.NoteEntity", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.HasOne("Bronistol.Database.DbEntities.PriorityEntity", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.HasOne("Bronistol.Database.DbEntities.ReasonEntity", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId");

                    b.HasOne("Bronistol.Database.DbEntities.DateEntity", "SubmitDate")
                        .WithMany()
                        .HasForeignKey("SubmitDateId");

                    b.Navigation("AssignedDate");

                    b.Navigation("Note");

                    b.Navigation("Priority");

                    b.Navigation("Reason");

                    b.Navigation("SubmitDate");
                });
#pragma warning restore 612, 618
        }
    }
}
