// <auto-generated />
using System;
using Bronistol.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bronistol.Database.Migrations
{
    [DbContext(typeof(BronistolContext))]
    [Migration("20210316160619_FixesDateEntity")]
    partial class FixesDateEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bronistol.Database.DbEntities.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AssignedDateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NameId")
                        .HasColumnType("integer");

                    b.Property<int?>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmitDateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDateId");

                    b.HasIndex("NameId");

                    b.HasIndex("NoteId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("SubmitDateId");

                    b.ToTable("BookingEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.DateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DateEntity");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.NameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NameEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NoteEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.PriorityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PriorityEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.ReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReasonEntities");
                });

            modelBuilder.Entity("Bronistol.Database.DbEntities.BookingEntity", b =>
                {
                    b.HasOne("Bronistol.Database.DbEntities.DateEntity", "AssignedDate")
                        .WithMany()
                        .HasForeignKey("AssignedDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bronistol.Database.DbEntities.NameEntity", "Name")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.HasOne("Bronistol.Database.DbEntities.NoteEntity", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.HasOne("Bronistol.Database.DbEntities.PriorityEntity", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.HasOne("Bronistol.Database.DbEntities.ReasonEntity", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId");

                    b.HasOne("Bronistol.Database.DbEntities.DateEntity", "SubmitDate")
                        .WithMany()
                        .HasForeignKey("SubmitDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDate");

                    b.Navigation("Name");

                    b.Navigation("Note");

                    b.Navigation("Priority");

                    b.Navigation("Reason");

                    b.Navigation("SubmitDate");
                });
#pragma warning restore 612, 618
        }
    }
}
